// <auto-generated />
namespace UMovies.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MovieFileExplicitDefinition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MovieFileExplicitDefinition));
        
        string IMigrationMetadata.Id
        {
            get { return "201707230242569_MovieFileExplicitDefinition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
